=== Adnane-BENABDELLAH/ProjetTechnologiesXML/Q2/Students/Cas GINF2/students.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Students (student)+ >
<!ELEMENT student (CNE, DateofBirth, FirstName, LastName, ClasseName, Phone, Email) >
<!ELEMENT CNE (#PCDATA) >
<!ELEMENT DateofBirth (#PCDATA) >
<!ELEMENT FirstName (#PCDATA) >
<!ELEMENT LastName (#PCDATA) >
<!ELEMENT ClasseName (#PCDATA) >
<!ELEMENT Phone (#PCDATA) >
<!ELEMENT Email (#PCDATA) >

=== Adnane-BENABDELLAH/ProjetTechnologiesXML/Q2/Students/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Students SYSTEM "students.dtd">
<Students>
    <Student>
        <CNE>K101</CNE>
        <DateofBirth>1/1/1997</DateofBirth>
        <FirstName>Hamid</FirstName>
        <LastName>SAMAOUI</LastName>
        <ClasseName>AP1</ClasseName>
        <Phone>+212 666148759</Phone>
        <Email>hamid@gmail.com</Email>
    </Student>
    
    <Student>
        <CNE>K102</CNE>
        <DateofBirth>1/1/1997</DateofBirth>
        <FirstName>Hanane</FirstName>
        <LastName>SAMAOUI</LastName>
        <ClasseName>AP1</ClasseName>
        <Phone>+212 666148759</Phone>
        <Email>hamid@gmail.com</Email>
    </Student>
</Students>

=== Adnane-BENABDELLAH/ProjetTechnologiesXML/Q1/XMLgeneratorStudents/xmlfiles/Students_GINF2.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE Students SYSTEM "students.dtd">
<Students>
  <student>
    <CNE>K128</CNE>
    <DateofBirth>01/10/1999</DateofBirth>
    <FirstName>Ahmed</FirstName>
    <LastName>BASSOU</LastName>
    <ClassseName>GINF2</ClassseName>
    <Phone>+212 666148751</Phone>
    <Email>ahmed@gmail.com</Email>
  </student>
  <student>
    <CNE>K129</CNE>
    <DateofBirth>12/07/2000</DateofBirth>
    <FirstName>Basma</FirstName>
    <LastName>MESBAHI</LastName>
    <ClassseName>GINF2</ClassseName>
    <Phone>+212 677578761</Phone>
    <Email>basma@gmail.com</Email>
  </student>
  <student>
    <CNE>K130</CNE>
    <DateofBirth>07/04/2000</DateofBirth>
    <FirstName>Marwa</FirstName>
    <LastName>GHANI</LastName>
    <ClassseName>GINF2</ClassseName>
    <Phone>+212 625148762</Phone>
    <Email>marwa@gmail.com</Email>
  </student>
</Students>
